In [34]:
import torch

x = torch.Tensor([0,3,1,2])
A = torch.Tensor([[-0.8,0.3,1,0.4],[-0.2,0.4,-0.3,-0.4],[0.2,1,-0.1,0.8]])
y = A @ x

# y = Dx
def orthogonal_matching_pursuit(compressed_vector, compression_matrix, sparsity):
    # initialize
    compression_matrix_norm = torch.norm(compression_matrix, dim=0, keepdim=True)
    unit_compression_matrix = compression_matrix / compression_matrix_norm
    subsapce_index_list = []
    residual = compressed_vector
    k = 1
    sparsity_vecotr = torch.zeros(compression_matrix.shape[1])
    err = torch.abs(residual).sum()
    while k <= sparsity and err > 1e-5:
        residual_projection_matrix = torch.abs(unit_compression_matrix.T @ residual)
        _, matching_basis_index = torch.max(residual_projection_matrix, dim=0)
        subsapce_index_list.append(matching_basis_index.item())
        subspace_matrix = compression_matrix[:, subsapce_index_list]
        subspace_matrix_pinv = torch.pinverse(subspace_matrix)
        subspace_coordinates = subspace_matrix_pinv @ compressed_vector
        subspace_representation = subspace_matrix @ subspace_coordinates
        residual = compressed_vector - subspace_representation
        err = torch.abs(residual).sum()
        k += 1
    sparsity_vecotr[subsapce_index_list] = subspace_coordinates
    return sparsity_vecotr, k

orthogonal_matching_pursuit(y,A, sparsity=3)


(tensor([0.0000, 3.0000, 1.0000, 2.0000]), 4)

In [39]:
y,x,A

(tensor([2.7000, 0.1000, 4.5000]),
 tensor([0., 3., 1., 2.]),
 tensor([[-0.8000,  0.3000,  1.0000,  0.4000],
         [-0.2000,  0.4000, -0.3000, -0.4000],
         [ 0.2000,  1.0000, -0.1000,  0.8000]]))

In [42]:
# Y = DX
# y = Dx
def orthogonal_matching_pursuit(compressed_vector, compression_matrix, sparsity):
    # initialize
    compression_matrix_norm = torch.norm(compression_matrix, dim=0, keepdim=True)
    unit_compression_matrix = compression_matrix / compression_matrix_norm
    subsapce_index_list = []
    residual = compressed_vector
    k = 1
    sparsity_vecotr = torch.zeros(compression_matrix.shape[1])
    err = torch.abs(residual).sum()
    while k <= sparsity and err > 1e-5:
        residual_projection_matrix = torch.abs(unit_compression_matrix.T @ residual)
        _, matching_basis_index = torch.max(residual_projection_matrix, dim=0)
        subsapce_index_list.append(matching_basis_index.item())
        subspace_matrix = compression_matrix[:, subsapce_index_list]
        subspace_matrix_pinv = torch.pinverse(subspace_matrix)
        subspace_coordinates = subspace_matrix_pinv @ compressed_vector
        subspace_representation = subspace_matrix @ subspace_coordinates
        residual = compressed_vector - subspace_representation
        err = torch.abs(residual).sum()
        k += 1
    sparsity_vecotr[subsapce_index_list] = subspace_coordinates
    return sparsity_vecotr, k

tensor([[ 1.0000e+00, -9.5894e-08,  2.0784e-09],
        [-8.8957e-08,  1.0000e+00,  1.5202e-07],
        [-3.8111e-08,  1.3046e-07,  1.0000e+00]])